import type { ToolDefinition } from "@/types/tool";

export const toolDefinitions: ToolDefinition[] = [
  // ── Images ──────────────────────────────────────────────
  {
    id: "image-jpg-to-webp",
    slug: "jpg-to-webp",
    name: "JPG to WebP",
    description:
      "Convert JPG and JPEG images to modern WebP format with high quality and small file size.",
    category: "images",
    aliases: ["jpeg to webp", "convert jpg", "jpeg webp"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 85,
        help: "Higher quality means larger files.",
      },
    ],
    keywords: ["jpg", "jpeg", "webp", "convert", "image"],
    relatedToolSlugs: [
      "png-to-webp",
      "compress-image",
      "resize-image",
      "webp-to-jpg",
    ],
    faq: [
      {
        question: "Does this upload my images to a server?",
        answer:
          "No. All conversion happens directly in your browser. Your files never leave your device.",
      },
      {
        question: "What quality should I use?",
        answer:
          "Quality 80-85 is a good balance between file size and visual quality for most photos.",
      },
    ],
    howItWorks: [
      "Upload one or more JPG images",
      "Choose a quality level",
      "Files are converted in your browser",
      "Download individual WebP files or all as a ZIP",
    ],
    available: true,
  },
  {
    id: "image-png-to-webp",
    slug: "png-to-webp",
    name: "PNG to WebP",
    description:
      "Convert PNG images to WebP format for smaller file sizes with transparency support.",
    category: "images",
    aliases: ["png webp", "convert png"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/png"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 85,
      },
    ],
    keywords: ["png", "webp", "convert", "image"],
    relatedToolSlugs: [
      "jpg-to-webp",
      "compress-image",
      "resize-image",
      "webp-to-png",
    ],
    available: true,
  },
  {
    id: "image-webp-to-jpg",
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    description: "Convert WebP images to JPG format for maximum compatibility.",
    category: "images",
    aliases: ["webp jpg", "convert webp"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 90,
      },
    ],
    keywords: ["webp", "jpg", "convert", "image"],
    relatedToolSlugs: ["jpg-to-webp", "png-to-webp", "compress-image"],
    available: true,
  },
  {
    id: "image-webp-to-png",
    slug: "webp-to-png",
    name: "WebP to PNG",
    description:
      "Convert WebP images to PNG format with full transparency support.",
    category: "images",
    aliases: ["webp png", "convert webp"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    keywords: ["webp", "png", "convert", "image"],
    relatedToolSlugs: ["png-to-webp", "webp-to-jpg", "compress-image"],
    available: true,
  },
  {
    id: "image-png-to-jpg",
    slug: "png-to-jpg",
    name: "PNG to JPG",
    description:
      "Convert PNG images to JPG format. Transparency is replaced with a white background.",
    category: "images",
    aliases: ["png jpg", "convert png"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/png"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 90,
      },
    ],
    keywords: ["png", "jpg", "convert", "image"],
    relatedToolSlugs: ["jpg-to-webp", "png-to-webp", "compress-image"],
    available: true,
  },
  {
    id: "image-compress",
    slug: "compress-image",
    name: "Compress Image",
    description:
      "Reduce the file size of JPG, PNG, and WebP images while maintaining good visual quality.",
    category: "images",
    aliases: ["optimize image", "reduce image size", "image optimizer"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 75,
        help: "Lower quality means smaller files.",
      },
    ],
    keywords: ["compress", "optimize", "reduce", "image", "size"],
    relatedToolSlugs: ["resize-image", "jpg-to-webp", "png-to-webp"],
    faq: [
      {
        question: "Does compression reduce image quality?",
        answer:
          "Yes, lossy compression reduces quality. Use a higher quality setting to preserve detail.",
      },
    ],
    howItWorks: [
      "Upload one or more images",
      "Set the quality level",
      "Images are compressed in your browser",
      "Download the optimized files",
    ],
    available: true,
  },
  {
    id: "image-resize",
    slug: "resize-image",
    name: "Resize Image",
    description:
      "Resize images to specific dimensions while maintaining aspect ratio.",
    category: "images",
    aliases: ["scale image", "shrink image", "image dimensions"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "maxWidth",
        label: "Max Width (px)",
        type: "number",
        default: 1920,
        help: "Images wider than this will be scaled down. Leave at 0 for no limit.",
      },
      {
        key: "maxHeight",
        label: "Max Height (px)",
        type: "number",
        default: 0,
        help: "Images taller than this will be scaled down. Leave at 0 for no limit.",
      },
      {
        key: "maintainAspect",
        label: "Maintain aspect ratio",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["resize", "scale", "dimensions", "image", "shrink"],
    relatedToolSlugs: ["compress-image", "jpg-to-webp", "png-to-webp"],
    available: true,
  },
  {
    id: "image-rotate",
    slug: "rotate-image",
    name: "Rotate Image",
    description:
      "Rotate images by 90°, 180°, 270° or a custom angle. Perfect for fixing orientation issues.",
    category: "images",
    aliases: ["turn image", "spin image", "rotate photo"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 50,
    options: [
      {
        key: "angle",
        label: "Rotation",
        type: "select",
        default: "90",
        options: [
          { label: "90° clockwise", value: "90" },
          { label: "180°", value: "180" },
          { label: "270° clockwise", value: "270" },
          { label: "Custom angle", value: "custom" },
        ],
      },
      {
        key: "customAngle",
        label: "Custom Angle",
        type: "number",
        default: 45,
        min: -360,
        max: 360,
      },
    ],
    keywords: ["rotate", "turn", "spin", "image", "orientation"],
    relatedToolSlugs: ["flip-image", "resize-image"],
    available: true,
  },
  {
    id: "image-flip",
    slug: "flip-image",
    name: "Flip Image",
    description:
      "Flip images horizontally or vertically. Useful for correcting mirrored photos.",
    category: "images",
    aliases: ["mirror image", "reflect image", "flip horizontal", "flip vertical"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 50,
    options: [
      {
        key: "direction",
        label: "Flip Direction",
        type: "select",
        default: "horizontal",
        options: [
          { label: "Horizontal (left ↔ right)", value: "horizontal" },
          { label: "Vertical (top ↔ bottom)", value: "vertical" },
          { label: "Both (180° rotation)", value: "both" },
        ],
      },
    ],
    keywords: ["flip", "mirror", "reflect", "image"],
    relatedToolSlugs: ["rotate-image", "resize-image"],
    available: true,
  },
  {
    id: "image-filters",
    slug: "image-filters",
    name: "Image Filters",
    description:
      "Apply filters and effects to images: grayscale, sepia, invert, blur, brightness, contrast and more.",
    category: "images",
    aliases: ["image effects", "photo filters", "grayscale", "sepia"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 50,
    options: [
      {
        key: "filter",
        label: "Filter",
        type: "select",
        default: "none",
        options: [
          { label: "None", value: "none" },
          { label: "Grayscale", value: "grayscale" },
          { label: "Sepia", value: "sepia" },
          { label: "Invert", value: "invert" },
          { label: "Blur", value: "blur" },
          { label: "Brightness", value: "brightness" },
          { label: "Contrast", value: "contrast" },
          { label: "Saturate", value: "saturate" },
          { label: "Hue Rotate", value: "hue" },
        ],
      },
      {
        key: "intensity",
        label: "Intensity",
        type: "slider",
        default: 100,
        min: 0,
        max: 200,
        step: 1,
        help: "Filter strength percentage",
      },
    ],
    keywords: ["filter", "effect", "grayscale", "sepia", "blur", "image"],
    relatedToolSlugs: ["compress-image", "rotate-image"],
    faq: [
      {
        question: "Can I apply multiple filters?",
        answer:
          "Yes, you can run the tool multiple times with different filters. Each filter is applied independently.",
      },
    ],
    available: true,
  },
  {
    id: "image-favicon",
    slug: "favicon-generator",
    name: "Favicon Generator",
    description:
      "Generate a favicon.ico file with multiple sizes from any image. Perfect for website icons.",
    category: "images",
    aliases: ["favicon", "website icon", "generate favicon", "ico generator"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 1,
    options: [
      {
        key: "sizes",
        label: "Include Sizes",
        type: "select",
        default: "all",
        options: [
          { label: "All sizes (16, 32, 48, 256)", value: "all" },
          { label: "Standard (16, 32, 48)", value: "standard" },
          { label: "Modern (32, 48, 256)", value: "modern" },
        ],
      },
    ],
    keywords: ["favicon", "icon", "website", "generator", "ico"],
    relatedToolSlugs: ["resize-image", "compress-image"],
    faq: [
      {
        question: "What is a favicon.ico?",
        answer:
          "A favicon is the small icon displayed in browser tabs. Modern browsers support PNG favicons too, but .ico provides the best compatibility.",
      },
    ],
    howItWorks: [
      "Upload an image",
      "Choose which sizes to include",
      "A favicon.ico is generated with all sizes",
      "Download and add to your website",
    ],
    available: true,
  },
  {
    id: "image-social",
    slug: "social-image-optimizer",
    name: "Social Image Optimizer",
    description:
      "Resize images to optimal dimensions for social media platforms. Instagram, LinkedIn, Twitter, Facebook and YouTube presets.",
    category: "images",
    aliases: ["social media image", "instagram size", "twitter image", "linkedin image"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 20,
    options: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        default: "instagram-post",
        options: [
          { label: "Instagram Post", value: "instagram-post" },
          { label: "Instagram Story", value: "instagram-story" },
          { label: "Instagram Profile", value: "instagram-profile" },
          { label: "Facebook Post", value: "facebook-post" },
          { label: "Facebook Cover", value: "facebook-cover" },
          { label: "Twitter Post", value: "twitter-post" },
          { label: "Twitter Header", value: "twitter-header" },
          { label: "LinkedIn Post", value: "linkedin-post" },
          { label: "LinkedIn Banner", value: "linkedin-banner" },
          { label: "YouTube Thumbnail", value: "youtube-thumbnail" },
          { label: "YouTube Channel Art", value: "youtube-channel" },
          { label: "Pinterest Pin", value: "pinterest-pin" },
        ],
      },
      {
        key: "maintainAspect",
        label: "Maintain aspect ratio",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["social", "instagram", "twitter", "facebook", "linkedin", "youtube", "image"],
    relatedToolSlugs: ["resize-image", "compress-image"],
    faq: [
      {
        question: "What sizes are available?",
        answer:
          "Each platform has optimized dimensions. For example: Instagram Post (1080×1080), Twitter Post (1200×675), YouTube Thumbnail (1280×720).",
      },
    ],
    available: true,
  },

  // ── PDF ─────────────────────────────────────────────────
  {
    id: "pdf-merge",
    slug: "merge-pdf",
    name: "Merge PDF",
    description:
      "Combine multiple PDF files into a single document. Reorder pages before merging.",
    category: "pdf",
    aliases: ["combine pdf", "join pdf", "pdf combiner"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/pdf"],
    maxFileSizeMB: 100,
    maxFiles: 50,
    keywords: ["merge", "combine", "join", "pdf"],
    relatedToolSlugs: ["split-pdf", "compress-image"],
    faq: [
      {
        question: "Is there a limit on the number of PDFs I can merge?",
        answer:
          "You can merge up to 50 PDFs at once. Each file can be up to 100 MB.",
      },
    ],
    howItWorks: [
      "Upload two or more PDF files",
      "Drag to reorder them",
      "Click Merge",
      "Download the combined PDF",
    ],
    available: true,
  },
  {
    id: "pdf-split",
    slug: "split-pdf",
    name: "Split PDF",
    description:
      "Extract pages or split a PDF into multiple files by page ranges.",
    category: "pdf",
    aliases: ["pdf extract", "pdf pages", "divide pdf"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
    options: [
      {
        key: "mode",
        label: "Split mode",
        type: "select",
        default: "ranges",
        options: [
          { label: "Page ranges", value: "ranges" },
          { label: "Each page separately", value: "each" },
          { label: "Every N pages", value: "interval" },
        ],
      },
      {
        key: "ranges",
        label: "Page ranges (e.g. 1-3, 5, 8-10)",
        type: "text",
        default: "1-3, 5, 8-10",
      },
      {
        key: "interval",
        label: "Pages per file",
        type: "number",
        default: 1,
      },
    ],
    keywords: ["split", "extract", "pages", "pdf"],
    relatedToolSlugs: ["merge-pdf"],
    available: true,
  },
  {
    id: "pdf-compress",
    slug: "compress-pdf",
    name: "Compress PDF",
    description:
      "Reduce PDF file size while maintaining quality. Removes unnecessary data, fonts, and metadata.",
    category: "pdf",
    aliases: ["pdf shrink", "pdf reduce", "pdf optimizer"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
    options: [
      {
        key: "level",
        label: "Compression Level",
        type: "select",
        default: "medium",
        options: [
          { label: "Low (best quality)", value: "low" },
          { label: "Medium (balanced)", value: "medium" },
          { label: "High (smallest size)", value: "high" },
        ],
      },
    ],
    keywords: ["compress", "shrink", "reduce", "size", "pdf"],
    relatedToolSlugs: ["merge-pdf", "split-pdf"],
    available: true,
  },
  {
    id: "pdf-rotate",
    slug: "rotate-pdf",
    name: "Rotate PDF Pages",
    description:
      "Rotate all pages or specific pages in a PDF by 90°, 180°, or 270°. Useful for fixing scanned documents.",
    category: "pdf",
    aliases: ["rotate pdf", "spin pdf", "turn pdf", "pdf orientation"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
    options: [
      {
        key: "angle",
        label: "Rotation",
        type: "select",
        default: "90",
        options: [
          { label: "90° clockwise", value: "90" },
          { label: "180°", value: "180" },
          { label: "270° clockwise", value: "270" },
        ],
      },
      {
        key: "allPages",
        label: "Apply to all pages",
        type: "switch",
        default: true,
      },
      {
        key: "pageRanges",
        label: "Page ranges (leave empty for all)",
        type: "text",
        default: "",
      },
    ],
    keywords: ["rotate", "turn", "spin", "orientation", "pdf"],
    relatedToolSlugs: ["split-pdf", "merge-pdf"],
    available: true,
  },
  {
    id: "pdf-to-images",
    slug: "pdf-to-images",
    name: "PDF to Images",
    description:
      "Convert PDF pages to PNG or JPEG images. Each page becomes a separate image file.",
    category: "pdf",
    aliases: ["pdf to png", "pdf to jpg", "pdf image", "export pdf"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
    options: [
      {
        key: "format",
        label: "Output Format",
        type: "select",
        default: "png",
        options: [
          { label: "PNG", value: "png" },
          { label: "JPEG", value: "jpeg" },
        ],
      },
      {
        key: "dpi",
        label: "Quality (DPI)",
        type: "select",
        default: "150",
        options: [
          { label: "72 DPI (screen)", value: "72" },
          { label: "150 DPI (standard)", value: "150" },
          { label: "300 DPI (print)", value: "300" },
        ],
      },
    ],
    keywords: ["pdf", "image", "convert", "export", "png", "jpg"],
    relatedToolSlugs: ["split-pdf", "merge-pdf"],
    available: true,
  },
  {
    id: "pdf-extract-images",
    slug: "extract-images",
    name: "Extract Images",
    description:
      "Extract all images embedded in a PDF. Images are saved with their original format preserved.",
    category: "pdf",
    aliases: ["pdf images", "extract image from pdf", "pdf photo"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
    keywords: ["pdf", "images", "extract", "photos", "pictures"],
    relatedToolSlugs: ["pdf-to-images", "split-pdf"],
    available: true,
  },

  // ── Files ───────────────────────────────────────────────
  {
    id: "files-zip-create",
    slug: "create-zip",
    name: "Create ZIP",
    description: "Compress multiple files into a single ZIP archive.",
    category: "files",
    aliases: ["zip files", "compress files", "archive"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: [],
    maxFileSizeMB: 500,
    maxFiles: 200,
    keywords: ["zip", "archive", "compress", "files"],
    relatedToolSlugs: ["extract-zip"],
    available: true,
  },
  {
    id: "files-zip-extract",
    slug: "extract-zip",
    name: "Extract ZIP",
    description:
      "Extract files from a ZIP archive and download them individually or as separate files.",
    category: "files",
    aliases: ["unzip", "decompress", "zip extractor"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/zip", "application/x-zip-compressed"],
    maxFileSizeMB: 500,
    maxFiles: 1,
    keywords: ["zip", "extract", "unzip", "decompress"],
    relatedToolSlugs: ["create-zip"],
    available: true,
  },
  {
    id: "files-zip-create-encrypted",
    slug: "create-encrypted-zip",
    name: "Password ZIP",
    description:
      "Create a password-protected ZIP archive. Files are encrypted with AES-256 for maximum security.",
    category: "files",
    aliases: ["encrypt zip", "password zip", "secure zip", "protected zip"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: [],
    maxFileSizeMB: 500,
    maxFiles: 200,
    options: [
      {
        key: "password",
        label: "Password",
        type: "text",
        default: "",
        help: "The password used to encrypt the ZIP archive.",
      },
    ],
    keywords: ["zip", "password", "encrypt", "secure", "archive"],
    relatedToolSlugs: ["create-zip", "extract-zip", "checksum-generator"],
    faq: [
      {
        question: "Is my password stored or sent anywhere?",
        answer:
          "No. Everything happens in your browser. The password is never sent to any server.",
      },
      {
        question: "What encryption is used?",
        answer:
          "AES-256 encryption is used, which is the strongest encryption available for ZIP files.",
      },
    ],
    howItWorks: [
      "Upload one or more files",
      "Enter a strong password",
      "A password-protected ZIP is created in your browser",
      "Download the encrypted ZIP file",
    ],
    available: true,
  },
  {
    id: "files-checksum",
    slug: "checksum-generator",
    name: "Checksum Generator",
    description:
      "Generate MD5, SHA-1, SHA-256, SHA-384 and SHA-512 hashes for any file. Verify data integrity instantly.",
    category: "files",
    aliases: ["file hash", "file integrity", "verify file", "hash file"],
    inputKind: "file",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: [],
    maxFileSizeMB: 500,
    maxFiles: 50,
    options: [
      {
        key: "algorithms",
        label: "Algorithms",
        type: "select",
        default: "all",
        options: [
          { label: "All algorithms", value: "all" },
          { label: "MD5 only", value: "md5" },
          { label: "SHA-1 only", value: "sha1" },
          { label: "SHA-256 only", value: "sha256" },
          { label: "SHA-384 only", value: "sha384" },
          { label: "SHA-512 only", value: "sha512" },
        ],
      },
    ],
    keywords: ["checksum", "hash", "md5", "sha", "integrity", "verify"],
    relatedToolSlugs: ["create-zip", "hash-generator"],
    faq: [
      {
        question: "Are my files uploaded to a server?",
        answer:
          "No. All hashing is performed locally in your browser using the Web Crypto API.",
      },
    ],
    howItWorks: [
      "Upload one or more files",
      "Select which hash algorithms to compute",
      "Hashes are generated in your browser",
      "Copy or download the checksums",
    ],
    available: true,
  },
  {
    id: "files-metadata",
    slug: "file-metadata",
    name: "File Metadata",
    description:
      "View detailed metadata for any file: type, size, MIME type, last modified date and more.",
    category: "files",
    aliases: ["file info", "file properties", "file details"],
    inputKind: "file",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: [],
    maxFileSizeMB: 500,
    maxFiles: 50,
    keywords: ["metadata", "file info", "properties", "details", "type"],
    relatedToolSlugs: ["checksum-generator", "create-zip"],
    faq: [
      {
        question: "What metadata is shown?",
        answer:
          "File name, size, type (MIME), last modified date, and file extension are displayed.",
      },
    ],
    howItWorks: [
      "Upload one or more files",
      "File metadata is read locally",
      "View detailed information about each file",
      "No data is uploaded",
    ],
    available: true,
  },

  // ── Developer ───────────────────────────────────────────
  {
    id: "dev-json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter",
    description:
      "Format, beautify and validate JSON. Indent with 2 or 4 spaces and catch syntax errors.",
    category: "developer",
    aliases: ["json beautifier", "pretty json", "format json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "indent",
        label: "Indent size",
        type: "select",
        default: "2",
        options: [
          { label: "2 spaces", value: "2" },
          { label: "4 spaces", value: "4" },
          { label: "Tab", value: "tab" },
        ],
      },
    ],
    keywords: ["json", "format", "beautify", "pretty", "validate"],
    relatedToolSlugs: [
      "json-minifier",
      "base64-encode-decode",
      "uuid-generator",
    ],
    available: true,
  },
  {
    id: "dev-json-minifier",
    slug: "json-minifier",
    name: "JSON Minifier",
    description:
      "Minify JSON by removing all unnecessary whitespace. Reduces file size for production.",
    category: "developer",
    aliases: ["compress json", "minify json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["json", "minify", "compress"],
    relatedToolSlugs: ["json-formatter"],
    available: true,
  },
  {
    id: "dev-base64",
    slug: "base64-encode-decode",
    name: "Base64 Encode / Decode",
    description:
      "Encode text to Base64 or decode Base64 back to text. Supports UTF-8.",
    category: "developer",
    aliases: ["base64", "encode", "decode"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "mode",
        label: "Mode",
        type: "select",
        default: "encode",
        options: [
          { label: "Encode", value: "encode" },
          { label: "Decode", value: "decode" },
        ],
      },
    ],
    keywords: ["base64", "encode", "decode"],
    relatedToolSlugs: ["json-formatter", "uuid-generator", "url-encode-decode"],
    available: true,
  },
  {
    id: "dev-uuid",
    slug: "uuid-generator",
    name: "UUID Generator",
    description:
      "Generate one or multiple UUIDs (v4). Copy them individually or all at once.",
    category: "developer",
    aliases: ["guid", "uuid v4", "unique id"],
    inputKind: "none",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "count",
        label: "Number of UUIDs",
        type: "number",
        default: 5,
        min: 1,
        max: 1000,
      },
      {
        key: "uppercase",
        label: "Uppercase",
        type: "switch",
        default: false,
      },
      {
        key: "hyphens",
        label: "Include hyphens",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["uuid", "guid", "unique", "id", "generate"],
    relatedToolSlugs: ["base64-encode-decode", "json-formatter"],
    available: true,
  },
  {
    id: "dev-url-encode",
    slug: "url-encode-decode",
    name: "URL Encode / Decode",
    description:
      "Encode text for safe use in URLs or decode URL-encoded strings.",
    category: "developer",
    aliases: ["percent encoding", "uri encode"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "mode",
        label: "Mode",
        type: "select",
        default: "encode",
        options: [
          { label: "Encode", value: "encode" },
          { label: "Decode", value: "decode" },
        ],
      },
    ],
    keywords: ["url", "encode", "decode", "percent", "uri"],
    relatedToolSlugs: ["base64-encode-decode"],
    available: true,
  },
  {
    id: "dev-hash",
    slug: "hash-generator",
    name: "Hash Generator",
    description:
      "Generate SHA-1, SHA-256, SHA-384, and SHA-512 hashes from text input.",
    category: "developer",
    aliases: ["sha256", "checksum", "digest"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        default: "SHA-256",
        options: [
          { label: "SHA-1", value: "SHA-1" },
          { label: "SHA-256", value: "SHA-256" },
          { label: "SHA-384", value: "SHA-384" },
          { label: "SHA-512", value: "SHA-512" },
        ],
      },
    ],
    keywords: ["hash", "sha", "checksum", "digest", "crypto"],
    relatedToolSlugs: ["uuid-generator", "base64-encode-decode"],
    available: true,
  },
  {
    id: "dev-json-schema",
    slug: "json-schema-generator",
    name: "JSON Schema Generator",
    description:
      "Generate a JSON Schema from sample JSON data. Infer types, formats, required fields and more.",
    category: "developer",
    aliases: ["json schema", "schema generator", "json type inference"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "required",
        label: "Mark required fields",
        type: "switch",
        default: true,
      },
      {
        key: "detectFormat",
        label: "Detect formats",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["json", "schema", "generator", "type", "developer"],
    relatedToolSlugs: ["json-formatter", "json-minifier"],
    available: true,
  },
  {
    id: "dev-yaml-formatter",
    slug: "yaml-formatter",
    name: "YAML Formatter",
    description:
      "Format and validate YAML. Detect syntax errors and format with proper indentation.",
    category: "developer",
    aliases: ["yaml beautifier", "pretty yaml", "format yaml", "yaml validator"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "indent",
        label: "Indent size",
        type: "select",
        default: "2",
        options: [
          { label: "2 spaces", value: "2" },
          { label: "4 spaces", value: "4" },
          { label: "Tab", value: "tab" },
        ],
      },
    ],
    keywords: ["yaml", "format", "beautify", "validate"],
    relatedToolSlugs: ["json-formatter"],
    available: true,
  },
  {
    id: "dev-jwt-decode",
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description:
      "Decode and inspect JSON Web Tokens (JWT). View header, payload and signature separately.",
    category: "developer",
    aliases: ["jwt", "json web token", "decode jwt", "jwt inspect"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["jwt", "token", "decode", "auth", "header", "payload"],
    relatedToolSlugs: ["base64-encode-decode", "hash-generator"],
    faq: [
      {
        question: "Does this verify the token signature?",
        answer:
          "No. This tool only decodes and displays the token contents. It cannot verify signatures without the secret.",
      },
    ],
    available: true,
  },
  {
    id: "dev-cron-parser",
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description:
      "Parse and validate cron expressions. See the next execution times and human-readable description.",
    category: "developer",
    aliases: ["cron", "cron expression", "cron job", "schedule", "crontab", "cron seconds"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["cron", "schedule", "parser", "crontab", "job", "time", "seconds"],
    relatedToolSlugs: ["timestamp-converter"],
    available: true,
  },
  {
    id: "dev-xml-formatter",
    slug: "xml-formatter",
    name: "XML Formatter",
    description:
      "Format, beautify and validate XML. Fix indentation and detect syntax errors.",
    category: "developer",
    aliases: ["xml beautifier", "pretty xml", "format xml", "xml validator"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "indent",
        label: "Indent size",
        type: "select",
        default: "2",
        options: [
          { label: "2 spaces", value: "2" },
          { label: "4 spaces", value: "4" },
          { label: "Tab", value: "tab" },
        ],
      },
    ],
    keywords: ["xml", "format", "beautify", "validate"],
    relatedToolSlugs: ["json-formatter"],
    available: true,
  },

  // ── Web ─────────────────────────────────────────────────
  {
    id: "web-qr-code",
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description:
      "Generate QR codes from any text or URL. Download as PNG or SVG.",
    category: "web",
    aliases: ["qr", "qrcode", "qr generator"],
    inputKind: "text",
    outputKind: "image",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "size",
        label: "Size (px)",
        type: "number",
        default: 256,
        min: 64,
        max: 1024,
      },
      {
        key: "margin",
        label: "Margin",
        type: "number",
        default: 4,
        min: 0,
        max: 10,
      },
      {
        key: "format",
        label: "Format",
        type: "select",
        default: "png",
        options: [
          { label: "PNG", value: "png" },
          { label: "SVG", value: "svg" },
        ],
      },
    ],
    keywords: ["qr", "qrcode", "barcode", "generate"],
    relatedToolSlugs: ["uuid-generator"],
    faq: [
      {
        question: "What can I encode in a QR code?",
        answer:
          "Any text: URLs, phone numbers, email addresses, Wi-Fi credentials, or plain text.",
      },
    ],
    available: true,
  },
  {
    id: "web-meta-tag",
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    description:
      "Generate SEO-friendly HTML meta tags for your website. Includes Open Graph, Twitter Cards and standard meta tags.",
    category: "web",
    aliases: ["meta tags", "seo", "open graph", "og tags", "twitter cards"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["meta", "tags", "seo", "open graph", "twitter"],
    relatedToolSlugs: ["qr-code-generator"],
    available: true,
  },
  {
    id: "web-robots",
    slug: "robots-generator",
    name: "Robots.txt Generator",
    description:
      "Generate a robots.txt file for your website. Control which pages search engines can crawl.",
    category: "web",
    aliases: ["robots txt", "robots.txt", "crawler", "seo", "search engine"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["robots", "txt", "crawler", "seo", "search engine"],
    relatedToolSlugs: ["meta-tag-generator", "sitemap"],
    available: true,
  },
  {
    id: "web-sitemap",
    slug: "sitemap-generator",
    name: "Sitemap Generator",
    description:
      "Generate an XML sitemap for your website. Just enter your URLs and get a ready-to-submit sitemap.xml.",
    category: "web",
    aliases: ["sitemap xml", "sitemap", "seo", "google search"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["sitemap", "xml", "seo", "google"],
    relatedToolSlugs: ["robots-generator", "meta-tag-generator"],
    available: true,
  },

  // ── Text ────────────────────────────────────────────────
  {
    id: "text-word-counter",
    slug: "word-counter",
    name: "Word Counter",
    description:
      "Count words, characters, sentences, paragraphs and estimate reading time.",
    category: "text",
    aliases: ["character counter", "count words", "text statistics"],
    inputKind: "text",
    outputKind: "none",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["word", "count", "character", "text", "reading time"],
    relatedToolSlugs: [
      "case-converter",
      "slug-generator",
      "whitespace-cleaner",
    ],
    available: true,
  },
  {
    id: "text-case-converter",
    slug: "case-converter",
    name: "Case Converter",
    description:
      "Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case and more.",
    category: "text",
    aliases: ["uppercase", "lowercase", "title case"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "case",
        label: "Case",
        type: "select",
        default: "upper",
        options: [
          { label: "UPPERCASE", value: "upper" },
          { label: "lowercase", value: "lower" },
          { label: "Title Case", value: "title" },
          { label: "camelCase", value: "camel" },
          { label: "PascalCase", value: "pascal" },
          { label: "snake_case", value: "snake" },
          { label: "kebab-case", value: "kebab" },
          { label: "Sentence case", value: "sentence" },
        ],
      },
    ],
    keywords: ["case", "uppercase", "lowercase", "convert", "text"],
    relatedToolSlugs: ["word-counter", "slug-generator", "whitespace-cleaner"],
    available: true,
  },
  {
    id: "text-slug-generator",
    slug: "slug-generator",
    name: "Slug Generator",
    description:
      "Convert text into URL-friendly slugs. Great for blog posts and page URLs.",
    category: "text",
    aliases: ["url slug", "permalink"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["slug", "url", "permalink", "seo"],
    relatedToolSlugs: ["case-converter", "word-counter"],
    available: true,
  },
  {
    id: "text-whitespace-cleaner",
    slug: "whitespace-cleaner",
    name: "Whitespace Cleaner",
    description:
      "Remove extra spaces, tabs, blank lines and trim whitespace from text.",
    category: "text",
    aliases: ["clean text", "remove spaces", "trim"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "trimLines",
        label: "Trim each line",
        type: "switch",
        default: true,
      },
      {
        key: "collapseSpaces",
        label: "Collapse multiple spaces",
        type: "switch",
        default: true,
      },
      {
        key: "removeBlankLines",
        label: "Remove blank lines",
        type: "switch",
        default: false,
      },
    ],
    keywords: ["whitespace", "clean", "trim", "spaces", "text"],
    relatedToolSlugs: ["word-counter", "case-converter"],
    available: true,
  },
  {
    id: "text-markdown-to-html",
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description:
      "Convert Markdown to HTML. Supports headings, lists, links, code blocks, tables and inline formatting.",
    category: "text",
    aliases: ["md to html", "markdown html", "convert markdown"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "includeDocType",
        label: "Include HTML doctype",
        type: "switch",
        default: false,
      },
    ],
    keywords: ["markdown", "html", "convert", "md", "document"],
    relatedToolSlugs: ["html-to-markdown", "html-minifier"],
    available: true,
  },
  {
    id: "text-html-to-markdown",
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description:
      "Convert HTML to Markdown. Extracts clean Markdown from HTML documents, stripping scripts and styles.",
    category: "text",
    aliases: ["html to md", "html markdown", "convert html"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["html", "markdown", "convert", "md"],
    relatedToolSlugs: ["markdown-to-html", "html-minifier"],
    available: true,
  },
  {
    id: "text-html-minifier",
    slug: "html-minifier",
    name: "HTML Minifier",
    description:
      "Minify HTML by removing comments, whitespace, and optional attributes. Reduces file size for production.",
    category: "text",
    aliases: ["minify html", "html minify", "compress html"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "removeComments",
        label: "Remove comments",
        type: "switch",
        default: true,
      },
      {
        key: "collapseWhitespace",
        label: "Collapse whitespace",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["html", "minify", "compress", "optimize"],
    relatedToolSlugs: ["markdown-to-html", "html-to-markdown"],
    available: true,
  },
  {
    id: "text-diff",
    slug: "text-diff",
    name: "Text Diff",
    description:
      "Compare two texts and highlight differences. See additions, deletions and modifications line by line.",
    category: "text",
    aliases: ["diff", "compare text", "text compare", "differences"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "mode",
        label: "Diff Mode",
        type: "select",
        default: "line",
        options: [
          { label: "Line by line", value: "line" },
          { label: "Word by word", value: "word" },
        ],
      },
    ],
    keywords: ["diff", "compare", "text", "differences", "change"],
    relatedToolSlugs: ["word-counter", "case-converter"],
    available: true,
  },

  // ── Colors ──────────────────────────────────────────────
  {
    id: "color-converter",
    slug: "color-converter",
    name: "Color Converter",
    description:
      "Convert colors between HEX, RGB, HSL and HSV formats with a live color picker.",
    category: "colors",
    aliases: ["hex rgb", "color picker", "hsl converter"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["color", "hex", "rgb", "hsl", "hsv", "convert"],
    relatedToolSlugs: ["contrast-checker"],
    available: true,
  },
  {
    id: "color-contrast",
    slug: "contrast-checker",
    name: "Contrast Checker",
    description:
      "Check WCAG color contrast ratios between two colors for accessibility compliance.",
    category: "colors",
    aliases: ["wcag", "accessibility", "color contrast"],
    inputKind: "text",
    outputKind: "none",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["contrast", "wcag", "accessibility", "color"],
    relatedToolSlugs: ["color-converter"],
    available: true,
  },

  // ── Date & Time ─────────────────────────────────────────
  {
    id: "datetime-timestamp",
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description:
      "Convert Unix timestamps to human-readable dates and vice versa across timezones.",
    category: "datetime",
    aliases: ["unix timestamp", "epoch converter"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["timestamp", "unix", "epoch", "date", "convert"],
    relatedToolSlugs: [],
    available: true,
  },

  // ── Converters ──────────────────────────────────────────
  {
    id: "converter-unit",
    slug: "unit-converter",
    name: "Unit Converter",
    description:
      "Convert between units of length, weight, temperature, speed, data size and more.",
    category: "converters",
    aliases: ["measurement", "metric", "imperial"],
    inputKind: "none",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "category",
        label: "Category",
        type: "select",
        default: "length",
        options: [
          { label: "Length", value: "length" },
          { label: "Weight", value: "weight" },
          { label: "Temperature", value: "temperature" },
          { label: "Speed", value: "speed" },
          { label: "Data Size", value: "data" },
          { label: "Area", value: "area" },
          { label: "Volume", value: "volume" },
        ],
      },
    ],
    keywords: ["unit", "convert", "measurement", "metric", "imperial"],
    relatedToolSlugs: [],
    available: true,
  },

  // ── Data ──────────────────────────────────────────────
  {
    id: "data-csv-to-json",
    slug: "csv-to-json",
    name: "CSV to JSON",
    description:
      "Convert CSV data to JSON format. Support for headers and nested objects.",
    category: "data",
    aliases: ["csv json", "convert csv", "csv to json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "separator",
        label: "Separator",
        type: "select",
        default: "comma",
        options: [
          { label: "Comma", value: "comma" },
          { label: "Semicolon", value: "semicolon" },
          { label: "Tab", value: "tab" },
          { label: "Pipe", value: "pipe" },
        ],
      },
      {
        key: "hasHeaders",
        label: "Has Headers",
        type: "switch",
        default: true,
      },
      {
        key: "normalizeHeaders",
        label: "Normalize Headers",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["csv", "json", "convert", "data"],
    relatedToolSlugs: ["json-to-csv", "csv-to-xml"],
    faq: [
      {
        question: "Can I convert large CSV files?",
        answer:
          "Yes, but very large files may be slow. For best results, keep files under 1MB.",
      },
      {
        question: "What if my CSV doesn't have headers?",
        answer:
          "Disable the 'Has Headers' option and the tool will generate generic column names (col1, col2, etc.).",
      },
    ],
    howItWorks: [
      "Paste or upload your CSV data",
      "Select separator and header options",
      "Data is converted in your browser",
      "Download the JSON file",
    ],
    available: true,
  },
  {
    id: "data-csv-to-xml",
    slug: "csv-to-xml",
    name: "CSV to XML",
    description:
      "Convert CSV data to XML format. Support for headers and nested objects with proper escaping.",
    category: "data",
    aliases: ["csv xml", "convert csv", "csv to xml"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "separator",
        label: "Separator",
        type: "select",
        default: "comma",
        options: [
          { label: "Comma", value: "comma" },
          { label: "Semicolon", value: "semicolon" },
          { label: "Tab", value: "tab" },
          { label: "Pipe", value: "pipe" },
        ],
      },
      {
        key: "hasHeaders",
        label: "Has Headers",
        type: "switch",
        default: true,
      },
      {
        key: "rootElement",
        label: "Root Element Name",
        type: "text",
        default: "data",
      },
    ],
    keywords: ["csv", "xml", "convert", "data"],
    relatedToolSlugs: ["json-to-csv", "xml-to-json"],
    available: true,
  },
  {
    id: "data-xml-to-json",
    slug: "xml-to-json",
    name: "XML to JSON",
    description:
      "Convert XML data to JSON format. Support for nested elements and attributes.",
    category: "data",
    aliases: ["xml json", "convert xml", "xml to json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "compact",
        label: "Compact Format",
        type: "switch",
        default: true,
        help: "Use xml-js compact format",
      },
      {
        key: "keepAttributes",
        label: "Keep Attributes",
        type: "switch",
        default: true,
        help: "Preserve XML attributes in the JSON output",
      },
    ],
    keywords: ["xml", "json", "convert", "data"],
    relatedToolSlugs: ["json-to-xml", "csv-to-xml", "json-to-yaml"],
    available: true,
  },
  {
    id: "data-json-to-xml",
    slug: "json-to-xml",
    name: "JSON to XML",
    description:
      "Convert JSON data to XML format. Supports nested objects, arrays, and custom root element.",
    category: "data",
    aliases: ["json xml", "convert json", "json to xml"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "compact",
        label: "Compact Format",
        type: "switch",
        default: false,
        help: "Output single-line compact XML instead of indented",
      },
      {
        key: "indentSize",
        label: "Indent Size",
        type: "select",
        default: "2",
        options: [
          { label: "2 spaces", value: "2" },
          { label: "4 spaces", value: "4" },
        ],
      },
      {
        key: "includeDeclaration",
        label: "XML Declaration",
        type: "switch",
        default: true,
        help: "Prepend <?xml version=\"1.0\" encoding=\"UTF-8\"?>",
      },
      {
        key: "rootElement",
        label: "Root Element Name",
        type: "text",
        default: "root",
      },
    ],
    keywords: ["json", "xml", "convert", "data"],
    relatedToolSlugs: ["xml-to-json", "json-to-csv", "json-to-yaml"],
    available: true,
  },
  {
    id: "data-json-to-toml",
    slug: "json-to-toml",
    name: "JSON to TOML",
    description:
      "Convert JSON objects to TOML format. Handles nested structures, arrays, and primitive values.",
    category: "data",
    aliases: ["json toml", "convert json", "json to toml"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [],
    keywords: ["json", "toml", "convert", "data"],
    relatedToolSlugs: ["toml-to-json", "json-to-yaml", "json-to-csv"],
    available: true,
  },
  {
    id: "data-toml-to-json",
    slug: "toml-to-json",
    name: "TOML to JSON",
    description:
      "Convert TOML data to JSON format. Supports nested tables, arrays, and all TOML data types.",
    category: "data",
    aliases: ["toml json", "convert toml", "toml to json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [],
    keywords: ["toml", "json", "convert", "data"],
    relatedToolSlugs: ["json-to-toml", "yaml-to-json", "csv-to-json"],
    available: true,
  },
  {
    id: "data-json-to-url-query",
    slug: "json-to-url-query",
    name: "JSON to URL Query",
    description:
      "Convert a JSON object into a URL query string. Supports nested objects and multiple array formats.",
    category: "data",
    aliases: ["json query", "querystring", "url params", "json to query string"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "arrayFormat",
        label: "Array Format",
        type: "select",
        default: "brackets",
        options: [
          { label: "Brackets (a[]=x&a[]=y)", value: "brackets" },
          { label: "Indices (a[0]=x&a[1]=y)", value: "indices" },
          { label: "Repeat (a=x&a=y)", value: "repeat" },
          { label: "Comma (a=x,y)", value: "comma" },
        ],
      },
      {
        key: "addPrefix",
        label: "Add ? Prefix",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["json", "url", "query", "querystring", "convert"],
    relatedToolSlugs: ["url-query-to-json", "json-to-xml"],
    available: true,
  },
  {
    id: "data-url-query-to-json",
    slug: "url-query-to-json",
    name: "URL Query to JSON",
    description:
      "Convert a URL query string into a JSON object. Supports nested keys, arrays, and configurable depth.",
    category: "data",
    aliases: ["query json", "querystring", "url params", "query string to json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "arrayFormat",
        label: "Array Format",
        type: "select",
        default: "brackets",
        options: [
          { label: "Brackets (a[]=x&a[]=y)", value: "brackets" },
          { label: "Indices (a[0]=x&a[1]=y)", value: "indices" },
          { label: "Repeat (a=x&a=y)", value: "repeat" },
          { label: "Comma (a=x,y)", value: "comma" },
        ],
      },
      {
        key: "depth",
        label: "Max Depth",
        type: "number",
        min: 1,
        max: 10,
        default: 5,
      },
    ],
    keywords: ["url", "query", "querystring", "json", "convert"],
    relatedToolSlugs: ["json-to-url-query", "json-to-xml"],
    available: true,
  },
  {
    id: "data-json-to-json-schema",
    slug: "json-to-json-schema",
    name: "JSON to JSON Schema",
    description:
      "Generate a draft-07 JSON Schema from a JSON sample. Infers types, properties, required fields, and string formats.",
    category: "data",
    aliases: ["json schema", "generate schema", "json to schema"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "inferRequired",
        label: "Mark All Properties Required",
        type: "switch",
        default: true,
      },
      {
        key: "detectFormat",
        label: "Detect String Formats",
        type: "switch",
        default: false,
        help: "Tag strings as email, date, date-time, uri, uuid, or ipv4 when they match",
      },
    ],
    keywords: ["json", "schema", "json schema", "validate", "convert"],
    relatedToolSlugs: ["json-to-sql", "json-to-csv", "json-formatter"],
    faq: [
      {
        question: "What dialect of JSON Schema is produced?",
        answer:
          "Draft-07. The output sets $schema to http://json-schema.org/draft-07/schema# and works with any draft-07 validator (e.g. ajv).",
      },
      {
        question: "How are mixed-type arrays handled?",
        answer:
          "If every item in an array has the same shape, the schema uses that shape as items. If items differ, the schema uses oneOf to enumerate the observed shapes.",
      },
    ],
    howItWorks: [
      "Paste your JSON sample",
      "Toggle required fields and string format detection",
      "The tool walks the value and emits a draft-07 schema",
      "Download the schema or feed it into any validator",
    ],
    available: true,
  },
  {
    id: "data-json-to-sql",
    slug: "json-to-sql",
    name: "JSON to SQL",
    description:
      "Generate CREATE TABLE and INSERT statements from a JSON array. Supports PostgreSQL, MySQL, and SQLite dialects.",
    category: "data",
    aliases: ["json sql", "sql insert", "json to sql", "create table"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "dialect",
        label: "SQL Dialect",
        type: "select",
        default: "postgres",
        options: [
          { label: "PostgreSQL", value: "postgres" },
          { label: "MySQL", value: "mysql" },
          { label: "SQLite", value: "sqlite" },
        ],
      },
      {
        key: "tableName",
        label: "Table Name",
        type: "text",
        default: "my_table",
      },
      {
        key: "includeDrop",
        label: "Include DROP TABLE",
        type: "switch",
        default: false,
      },
      {
        key: "includeCreate",
        label: "Include CREATE TABLE",
        type: "switch",
        default: true,
      },
      {
        key: "batchInserts",
        label: "Batch INSERT (single statement)",
        type: "switch",
        default: false,
      },
    ],
    keywords: ["json", "sql", "insert", "create table", "convert", "database"],
    relatedToolSlugs: ["json-to-json-schema", "json-to-csv", "csv-to-json"],
    faq: [
      {
        question: "How are types inferred?",
        answer:
          "Types are inferred from the first row: integer → INTEGER/BIGINT, decimal number → NUMERIC/DOUBLE, boolean → BOOLEAN/TINYINT(1), string → TEXT. Nested objects and arrays become TEXT or JSON depending on dialect.",
      },
      {
        question: "What if my objects have different keys?",
        answer:
          "All keys across all objects are unioned into the column list. Missing values in a row become NULL in the INSERT.",
      },
    ],
    howItWorks: [
      "Paste an array of JSON objects",
      "Pick a dialect, table name, and statement options",
      "Click Generate SQL",
      "Download or copy the resulting script",
    ],
    available: true,
  },
  {
    id: "data-json-to-yaml",
    slug: "json-to-yaml",
    name: "JSON to YAML",
    description:
      "Convert JSON data to YAML format. Supports arrays of objects and nested structures with proper indentation.",
    category: "data",
    aliases: ["json yaml", "convert json", "json to yaml"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "indentSize",
        label: "Indent Size",
        type: "select",
        default: "2",
        options: [
          { label: "2 spaces", value: "2" },
          { label: "4 spaces", value: "4" },
          { label: "Tab", value: "tab" },
        ],
      },
      {
        key: "pretty",
        label: "Pretty Print",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["json", "yaml", "convert", "data"],
    relatedToolSlugs: ["xml-to-json", "yaml-to-json"],
    available: true,
  },
  {
    id: "data-yaml-to-json",
    slug: "yaml-to-json",
    name: "YAML to JSON",
    description:
      "Convert YAML data to JSON format. Support for nested structures and complex data types.",
    category: "data",
    aliases: ["yaml json", "convert yaml", "yaml to json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "keepComments",
        label: "Keep Comments",
        type: "switch",
        default: false,
        help: "Preserve comments from YAML in the JSON output",
      },
      {
        key: "preserveOrder",
        label: "Preserve Order",
        type: "switch",
        default: false,
        help: "Maintain original key order when converting to JSON",
      },
    ],
    keywords: ["yaml", "json", "convert", "data"],
    relatedToolSlugs: ["json-to-yaml"],
    available: true,
  },
  {
    id: "data-json-to-csv",
    slug: "json-to-csv",
    name: "JSON to CSV",
    description:
      "Convert JSON data to CSV format. Supports arrays of objects with flexible formatting.",
    category: "data",
    aliases: ["json csv", "convert json", "json to csv"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "separator",
        label: "Separator",
        type: "select",
        default: "comma",
        options: [
          { label: "Comma", value: "comma" },
          { label: "Semicolon", value: "semicolon" },
          { label: "Tab", value: "tab" },
        ],
      },
      {
        key: "flattenNested",
        label: "Flatten Nested Objects",
        type: "switch",
        default: false,
        help: "Converts nested objects into dot-notation CSV rows",
      },
      {
        key: "consistentColumns",
        label: "Consistent Columns",
        type: "switch",
        default: true,
        help: "Ensures all objects have the same column set",
      },
    ],
    keywords: ["json", "csv", "convert", "data"],
    relatedToolSlugs: ["csv-to-json", "csv-to-xml"],
    faq: [
      {
        question: "Can I convert nested JSON to CSV?",
        answer:
          "Yes, enable 'Flatten Nested Objects' to convert nested structures into dot-notation CSV rows.",
      },
      {
        question: "What if my JSON objects have different keys?",
        answer:
          "Enable 'Consistent Columns' to include all keys across all objects, filling missing values with empty strings.",
      },
    ],
    howItWorks: [
      "Paste or upload your JSON data",
      "Select separator and formatting options",
      "Data is converted in your browser",
      "Download the CSV file",
    ],
    available: true,
  },
];

if (process.env.NODE_ENV !== "production") {
  const seenSlugs = new Set<string>();
  const seenIds = new Set<string>();
  for (const tool of toolDefinitions) {
    if (seenSlugs.has(tool.slug)) {
      console.error(`Duplicate tool slug: "${tool.slug}"`);
    }
    if (seenIds.has(tool.id)) {
      console.error(`Duplicate tool id: "${tool.id}"`);
    }
    seenSlugs.add(tool.slug);
    seenIds.add(tool.id);
  }
}

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return toolDefinitions.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return toolDefinitions.filter((t) => t.category === category);
}

export function getRelatedTools(tool: ToolDefinition): ToolDefinition[] {
  const related = (tool.relatedToolSlugs ?? [])
    .map((slug) => getToolBySlug(slug))
    .filter((t): t is ToolDefinition => t !== undefined);
  if (related.length < 4) {
    const sameCategory = toolDefinitions
      .filter(
        (t) =>
          t.category === tool.category &&
          t.id !== tool.id &&
          !related.includes(t),
      )
      .slice(0, 4 - related.length);
    return [...related, ...sameCategory];
  }
  return related;
}
