import type { ToolDefinition } from "@/types/tool";

export const toolDefinitions: ToolDefinition[] = [
  // ── Images ──────────────────────────────────────────────
  {
    id: "image-jpg-to-webp",
    slug: "jpg-to-webp",
    name: "JPG to WebP",
    description:
      "Convert JPG and JPEG images to modern WebP format with high quality and small file size.",
    category: "images",
    aliases: ["jpeg to webp", "convert jpg", "jpeg webp"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 85,
        help: "Higher quality means larger files.",
      },
    ],
    keywords: ["jpg", "jpeg", "webp", "convert", "image"],
    relatedToolSlugs: [
      "png-to-webp",
      "compress-image",
      "resize-image",
      "webp-to-jpg",
    ],
    faq: [
      {
        question: "Does this upload my images to a server?",
        answer:
          "No. All conversion happens directly in your browser. Your files never leave your device.",
      },
      {
        question: "What quality should I use?",
        answer:
          "Quality 80-85 is a good balance between file size and visual quality for most photos.",
      },
    ],
    howItWorks: [
      "Upload one or more JPG images",
      "Choose a quality level",
      "Files are converted in your browser",
      "Download individual WebP files or all as a ZIP",
    ],
    available: true,
  },
  {
    id: "image-png-to-webp",
    slug: "png-to-webp",
    name: "PNG to WebP",
    description:
      "Convert PNG images to WebP format for smaller file sizes with transparency support.",
    category: "images",
    aliases: ["png webp", "convert png"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/png"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 85,
      },
    ],
    keywords: ["png", "webp", "convert", "image"],
    relatedToolSlugs: [
      "jpg-to-webp",
      "compress-image",
      "resize-image",
      "webp-to-png",
    ],
    available: true,
  },
  {
    id: "image-webp-to-jpg",
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    description: "Convert WebP images to JPG format for maximum compatibility.",
    category: "images",
    aliases: ["webp jpg", "convert webp"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 90,
      },
    ],
    keywords: ["webp", "jpg", "convert", "image"],
    relatedToolSlugs: ["jpg-to-webp", "png-to-webp", "compress-image"],
    available: true,
  },
  {
    id: "image-webp-to-png",
    slug: "webp-to-png",
    name: "WebP to PNG",
    description:
      "Convert WebP images to PNG format with full transparency support.",
    category: "images",
    aliases: ["webp png", "convert webp"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    keywords: ["webp", "png", "convert", "image"],
    relatedToolSlugs: ["png-to-webp", "webp-to-jpg", "compress-image"],
    available: true,
  },
  {
    id: "image-png-to-jpg",
    slug: "png-to-jpg",
    name: "PNG to JPG",
    description:
      "Convert PNG images to JPG format. Transparency is replaced with a white background.",
    category: "images",
    aliases: ["png jpg", "convert png"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/png"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 90,
      },
    ],
    keywords: ["png", "jpg", "convert", "image"],
    relatedToolSlugs: ["jpg-to-webp", "png-to-webp", "compress-image"],
    available: true,
  },
  {
    id: "image-compress",
    slug: "compress-image",
    name: "Compress Image",
    description:
      "Reduce the file size of JPG, PNG, and WebP images while maintaining good visual quality.",
    category: "images",
    aliases: ["optimize image", "reduce image size", "image optimizer"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "quality",
        label: "Quality",
        type: "slider",
        min: 10,
        max: 100,
        step: 1,
        default: 75,
        help: "Lower quality means smaller files.",
      },
    ],
    keywords: ["compress", "optimize", "reduce", "image", "size"],
    relatedToolSlugs: ["resize-image", "jpg-to-webp", "png-to-webp"],
    faq: [
      {
        question: "Does compression reduce image quality?",
        answer:
          "Yes, lossy compression reduces quality. Use a higher quality setting to preserve detail.",
      },
    ],
    howItWorks: [
      "Upload one or more images",
      "Set the quality level",
      "Images are compressed in your browser",
      "Download the optimized files",
    ],
    available: true,
  },
  {
    id: "image-resize",
    slug: "resize-image",
    name: "Resize Image",
    description:
      "Resize images to specific dimensions while maintaining aspect ratio.",
    category: "images",
    aliases: ["scale image", "shrink image", "image dimensions"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: true,
    requiresAuthentication: false,
    acceptFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 50,
    maxFiles: 100,
    options: [
      {
        key: "maxWidth",
        label: "Max Width (px)",
        type: "number",
        default: 1920,
        help: "Images wider than this will be scaled down. Leave at 0 for no limit.",
      },
      {
        key: "maxHeight",
        label: "Max Height (px)",
        type: "number",
        default: 0,
        help: "Images taller than this will be scaled down. Leave at 0 for no limit.",
      },
      {
        key: "maintainAspect",
        label: "Maintain aspect ratio",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["resize", "scale", "dimensions", "image", "shrink"],
    relatedToolSlugs: ["compress-image", "jpg-to-webp", "png-to-webp"],
    available: true,
  },

  // ── PDF ─────────────────────────────────────────────────
  {
    id: "pdf-merge",
    slug: "merge-pdf",
    name: "Merge PDF",
    description:
      "Combine multiple PDF files into a single document. Reorder pages before merging.",
    category: "pdf",
    aliases: ["combine pdf", "join pdf", "pdf combiner"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/pdf"],
    maxFileSizeMB: 100,
    maxFiles: 50,
    keywords: ["merge", "combine", "join", "pdf"],
    relatedToolSlugs: ["split-pdf", "compress-image"],
    faq: [
      {
        question: "Is there a limit on the number of PDFs I can merge?",
        answer:
          "You can merge up to 50 PDFs at once. Each file can be up to 100 MB.",
      },
    ],
    howItWorks: [
      "Upload two or more PDF files",
      "Drag to reorder them",
      "Click Merge",
      "Download the combined PDF",
    ],
    available: true,
  },
  {
    id: "pdf-split",
    slug: "split-pdf",
    name: "Split PDF",
    description:
      "Extract pages or split a PDF into multiple files by page ranges.",
    category: "pdf",
    aliases: ["pdf extract", "pdf pages", "divide pdf"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/pdf"],
    maxFileSizeMB: 100,
    maxFiles: 1,
    options: [
      {
        key: "mode",
        label: "Split mode",
        type: "select",
        default: "ranges",
        options: [
          { label: "Page ranges", value: "ranges" },
          { label: "Each page separately", value: "each" },
          { label: "Every N pages", value: "interval" },
        ],
      },
      {
        key: "ranges",
        label: "Page ranges (e.g. 1-3, 5, 8-10)",
        type: "text",
        default: "1-3, 5, 8-10",
      },
      {
        key: "interval",
        label: "Pages per file",
        type: "number",
        default: 1,
      },
    ],
    keywords: ["split", "extract", "pages", "pdf"],
    relatedToolSlugs: ["merge-pdf"],
    available: true,
  },

  // ── Files ───────────────────────────────────────────────
  {
    id: "files-zip-create",
    slug: "create-zip",
    name: "Create ZIP",
    description: "Compress multiple files into a single ZIP archive.",
    category: "files",
    aliases: ["zip files", "compress files", "archive"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: [],
    maxFileSizeMB: 500,
    maxFiles: 200,
    keywords: ["zip", "archive", "compress", "files"],
    relatedToolSlugs: ["extract-zip"],
    available: true,
  },
  {
    id: "files-zip-extract",
    slug: "extract-zip",
    name: "Extract ZIP",
    description:
      "Extract files from a ZIP archive and download them individually or as separate files.",
    category: "files",
    aliases: ["unzip", "decompress", "zip extractor"],
    inputKind: "file",
    outputKind: "file",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    acceptFileTypes: ["application/zip", "application/x-zip-compressed"],
    maxFileSizeMB: 500,
    maxFiles: 1,
    keywords: ["zip", "extract", "unzip", "decompress"],
    relatedToolSlugs: ["create-zip"],
    available: true,
  },

  // ── Developer ───────────────────────────────────────────
  {
    id: "dev-json-formatter",
    slug: "json-formatter",
    name: "JSON Formatter",
    description:
      "Format, beautify and validate JSON. Indent with 2 or 4 spaces and catch syntax errors.",
    category: "developer",
    aliases: ["json beautifier", "pretty json", "format json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "indent",
        label: "Indent size",
        type: "select",
        default: "2",
        options: [
          { label: "2 spaces", value: "2" },
          { label: "4 spaces", value: "4" },
          { label: "Tab", value: "tab" },
        ],
      },
    ],
    keywords: ["json", "format", "beautify", "pretty", "validate"],
    relatedToolSlugs: [
      "json-minifier",
      "base64-encode-decode",
      "uuid-generator",
    ],
    available: true,
  },
  {
    id: "dev-json-minifier",
    slug: "json-minifier",
    name: "JSON Minifier",
    description:
      "Minify JSON by removing all unnecessary whitespace. Reduces file size for production.",
    category: "developer",
    aliases: ["compress json", "minify json"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["json", "minify", "compress"],
    relatedToolSlugs: ["json-formatter"],
    available: true,
  },
  {
    id: "dev-base64",
    slug: "base64-encode-decode",
    name: "Base64 Encode / Decode",
    description:
      "Encode text to Base64 or decode Base64 back to text. Supports UTF-8.",
    category: "developer",
    aliases: ["base64", "encode", "decode"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "mode",
        label: "Mode",
        type: "select",
        default: "encode",
        options: [
          { label: "Encode", value: "encode" },
          { label: "Decode", value: "decode" },
        ],
      },
    ],
    keywords: ["base64", "encode", "decode"],
    relatedToolSlugs: ["json-formatter", "uuid-generator", "url-encode-decode"],
    available: true,
  },
  {
    id: "dev-uuid",
    slug: "uuid-generator",
    name: "UUID Generator",
    description:
      "Generate one or multiple UUIDs (v4). Copy them individually or all at once.",
    category: "developer",
    aliases: ["guid", "uuid v4", "unique id"],
    inputKind: "none",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "count",
        label: "Number of UUIDs",
        type: "number",
        default: 5,
        min: 1,
        max: 1000,
      },
      {
        key: "uppercase",
        label: "Uppercase",
        type: "switch",
        default: false,
      },
      {
        key: "hyphens",
        label: "Include hyphens",
        type: "switch",
        default: true,
      },
    ],
    keywords: ["uuid", "guid", "unique", "id", "generate"],
    relatedToolSlugs: ["base64-encode-decode", "json-formatter"],
    available: true,
  },
  {
    id: "dev-url-encode",
    slug: "url-encode-decode",
    name: "URL Encode / Decode",
    description:
      "Encode text for safe use in URLs or decode URL-encoded strings.",
    category: "developer",
    aliases: ["percent encoding", "uri encode"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "mode",
        label: "Mode",
        type: "select",
        default: "encode",
        options: [
          { label: "Encode", value: "encode" },
          { label: "Decode", value: "decode" },
        ],
      },
    ],
    keywords: ["url", "encode", "decode", "percent", "uri"],
    relatedToolSlugs: ["base64-encode-decode"],
    available: true,
  },
  {
    id: "dev-hash",
    slug: "hash-generator",
    name: "Hash Generator",
    description:
      "Generate SHA-1, SHA-256, SHA-384, and SHA-512 hashes from text input.",
    category: "developer",
    aliases: ["sha256", "checksum", "digest"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        default: "SHA-256",
        options: [
          { label: "SHA-1", value: "SHA-1" },
          { label: "SHA-256", value: "SHA-256" },
          { label: "SHA-384", value: "SHA-384" },
          { label: "SHA-512", value: "SHA-512" },
        ],
      },
    ],
    keywords: ["hash", "sha", "checksum", "digest", "crypto"],
    relatedToolSlugs: ["uuid-generator", "base64-encode-decode"],
    available: true,
  },

  // ── Web ─────────────────────────────────────────────────
  {
    id: "web-qr-code",
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description:
      "Generate QR codes from any text or URL. Download as PNG or SVG.",
    category: "web",
    aliases: ["qr", "qrcode", "qr generator"],
    inputKind: "text",
    outputKind: "image",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "size",
        label: "Size (px)",
        type: "number",
        default: 256,
        min: 64,
        max: 1024,
      },
      {
        key: "margin",
        label: "Margin",
        type: "number",
        default: 4,
        min: 0,
        max: 10,
      },
      {
        key: "format",
        label: "Format",
        type: "select",
        default: "png",
        options: [
          { label: "PNG", value: "png" },
          { label: "SVG", value: "svg" },
        ],
      },
    ],
    keywords: ["qr", "qrcode", "barcode", "generate"],
    relatedToolSlugs: ["uuid-generator"],
    faq: [
      {
        question: "What can I encode in a QR code?",
        answer:
          "Any text: URLs, phone numbers, email addresses, Wi-Fi credentials, or plain text.",
      },
    ],
    available: true,
  },

  // ── Text ────────────────────────────────────────────────
  {
    id: "text-word-counter",
    slug: "word-counter",
    name: "Word Counter",
    description:
      "Count words, characters, sentences, paragraphs and estimate reading time.",
    category: "text",
    aliases: ["character counter", "count words", "text statistics"],
    inputKind: "text",
    outputKind: "none",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["word", "count", "character", "text", "reading time"],
    relatedToolSlugs: [
      "case-converter",
      "slug-generator",
      "whitespace-cleaner",
    ],
    available: true,
  },
  {
    id: "text-case-converter",
    slug: "case-converter",
    name: "Case Converter",
    description:
      "Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case and more.",
    category: "text",
    aliases: ["uppercase", "lowercase", "title case"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "case",
        label: "Case",
        type: "select",
        default: "upper",
        options: [
          { label: "UPPERCASE", value: "upper" },
          { label: "lowercase", value: "lower" },
          { label: "Title Case", value: "title" },
          { label: "camelCase", value: "camel" },
          { label: "PascalCase", value: "pascal" },
          { label: "snake_case", value: "snake" },
          { label: "kebab-case", value: "kebab" },
          { label: "Sentence case", value: "sentence" },
        ],
      },
    ],
    keywords: ["case", "uppercase", "lowercase", "convert", "text"],
    relatedToolSlugs: ["word-counter", "slug-generator", "whitespace-cleaner"],
    available: true,
  },
  {
    id: "text-slug-generator",
    slug: "slug-generator",
    name: "Slug Generator",
    description:
      "Convert text into URL-friendly slugs. Great for blog posts and page URLs.",
    category: "text",
    aliases: ["url slug", "permalink"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["slug", "url", "permalink", "seo"],
    relatedToolSlugs: ["case-converter", "word-counter"],
    available: true,
  },
  {
    id: "text-whitespace-cleaner",
    slug: "whitespace-cleaner",
    name: "Whitespace Cleaner",
    description:
      "Remove extra spaces, tabs, blank lines and trim whitespace from text.",
    category: "text",
    aliases: ["clean text", "remove spaces", "trim"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "trimLines",
        label: "Trim each line",
        type: "switch",
        default: true,
      },
      {
        key: "collapseSpaces",
        label: "Collapse multiple spaces",
        type: "switch",
        default: true,
      },
      {
        key: "removeBlankLines",
        label: "Remove blank lines",
        type: "switch",
        default: false,
      },
    ],
    keywords: ["whitespace", "clean", "trim", "spaces", "text"],
    relatedToolSlugs: ["word-counter", "case-converter"],
    available: true,
  },

  // ── Colors ──────────────────────────────────────────────
  {
    id: "color-converter",
    slug: "color-converter",
    name: "Color Converter",
    description:
      "Convert colors between HEX, RGB, HSL and HSV formats with a live color picker.",
    category: "colors",
    aliases: ["hex rgb", "color picker", "hsl converter"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["color", "hex", "rgb", "hsl", "hsv", "convert"],
    relatedToolSlugs: ["contrast-checker"],
    available: true,
  },
  {
    id: "color-contrast",
    slug: "contrast-checker",
    name: "Contrast Checker",
    description:
      "Check WCAG color contrast ratios between two colors for accessibility compliance.",
    category: "colors",
    aliases: ["wcag", "accessibility", "color contrast"],
    inputKind: "text",
    outputKind: "none",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["contrast", "wcag", "accessibility", "color"],
    relatedToolSlugs: ["color-converter"],
    available: true,
  },

  // ── Date & Time ─────────────────────────────────────────
  {
    id: "datetime-timestamp",
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    description:
      "Convert Unix timestamps to human-readable dates and vice versa across timezones.",
    category: "datetime",
    aliases: ["unix timestamp", "epoch converter"],
    inputKind: "text",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    keywords: ["timestamp", "unix", "epoch", "date", "convert"],
    relatedToolSlugs: [],
    available: true,
  },

  // ── Converters ──────────────────────────────────────────
  {
    id: "converter-unit",
    slug: "unit-converter",
    name: "Unit Converter",
    description:
      "Convert between units of length, weight, temperature, speed, data size and more.",
    category: "converters",
    aliases: ["measurement", "metric", "imperial"],
    inputKind: "none",
    outputKind: "text",
    processingMode: "client",
    supportsBatch: false,
    requiresAuthentication: false,
    options: [
      {
        key: "category",
        label: "Category",
        type: "select",
        default: "length",
        options: [
          { label: "Length", value: "length" },
          { label: "Weight", value: "weight" },
          { label: "Temperature", value: "temperature" },
          { label: "Speed", value: "speed" },
          { label: "Data Size", value: "data" },
          { label: "Area", value: "area" },
          { label: "Volume", value: "volume" },
        ],
      },
    ],
    keywords: ["unit", "convert", "measurement", "metric", "imperial"],
    relatedToolSlugs: [],
    available: true,
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return toolDefinitions.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return toolDefinitions.filter((t) => t.category === category);
}

export function getRelatedTools(tool: ToolDefinition): ToolDefinition[] {
  const related = (tool.relatedToolSlugs ?? [])
    .map((slug) => getToolBySlug(slug))
    .filter((t): t is ToolDefinition => t !== undefined);
  if (related.length < 4) {
    const sameCategory = toolDefinitions
      .filter(
        (t) =>
          t.category === tool.category &&
          t.id !== tool.id &&
          !related.includes(t),
      )
      .slice(0, 4 - related.length);
    return [...related, ...sameCategory];
  }
  return related;
}
